### ISSUE TITLE
Better formatting for Privilege Escalation findings

### ISSUE THREAD

**Issue by kmcquade** [salesforce/cloudsplaining#114]
In the UI, the Privilege Escalation is in raw format. It looks like this:

![image](https://user-images.githubusercontent.com/3422255/95111473-8d359380-070d-11eb-9e98-f1f5aa446cdb.png)

While some AWS Security professionals might notice what `EditExistingLambdaFunctionWithRole` means, or they might have read the documentation stating that we use the Rhino Security Labs research for this, this is not obvious upon viewing this information for the first time. We should format the output so that it explains this for the user.

https://github.com/salesforce/cloudsplaining/blob/master/cloudsplaining/output/src/components/finding/PrivilegeEscalationDetails.vue#L11

**Comment by rohanshenoy96** [comment]
Can you give more information on how exactly you need it to be formatted.

**Comment by kmcquade** [comment]
I am working on this one and can take care of this.
