### ISSUE TITLE
Inline Explanation of findings

### ISSUE THREAD

**Issue by kmcquade** [salesforce/cloudsplaining#115]
On the Customer Managed Policies page of the example report, we have a lot of raw formatted arrays that don't mean much until you look at the Guidance or Appendices.

![image](https://user-images.githubusercontent.com/3422255/95111683-d84fa680-070d-11eb-9ce9-6808b4a4da51.png)

We should provide a little explanation of what these details mean in those fields. Should be a short, obvious, non-intrusive piece of text.

**Comment by kmcquade** [comment]
The file where we list those details is here:

https://github.com/salesforce/cloudsplaining/blob/0ae7ea507cd32e7b64e0e8982f2902b6f76dfa77/cloudsplaining/output/src/components/finding/StandardRiskDetails.vue#L3-L22

**Comment by rohanshenoy96** [comment]
Hi @kmcquade. If you can give more details, I'll be happy to add them
