### ISSUE TITLE
Implementing Vue Routers?

### ISSUE THREAD

**Issue by kmcquade** [salesforce/cloudsplaining#116]
A few users have commented that it would be nice to be able to click on a link to a policy, and then the report brings you right to the finding. That isn't currently possible in the report. I **think** the right way to do this is Vue Routers, which is not something I have explored yet.

This would greatly help the user experience, so any help is welcome!

**Comment by rohanshenoy96** [comment]
Hi @kmcquade. Can you please share some more details.

**Comment by kmcquade** [comment]
@rohanshenoy96 what is your experience with Vue?

Check out the example report. https://opensource.salesforce.com/cloudsplaining/. Click on one of the tabs at the top, then refresh the page, and notice how it brings you back to the summary tab, even if you were on a different tab.

Personally, I'm new to Vue - had to learn it for this project, actually - and I never got to the point where I was using Vue Routers, but I think that looks like the right way to do it (but I could be wrong). Happy to get any suggestions on how to deal with this.

**Comment by kmcquade** [comment]
This would be most useful for viewing policies attached to a principal. For example, when you click on the Principals tab, hit "Show" for a Principal, then click on the Inline, Customer Managed, or AWS managed policies, it only shows you the name of a Policy right now - it doesn't show you a hyperlink to that Policy because we currently don't have a way to switch tabs based on the href lol.

**Comment by rohanshenoy96** [comment]
Yes you are right Routers will be the best way to achieve this. I can work on this, please assign it to me.

**Comment by kmcquade** [comment]
Great! Assigned. :)

**Comment by rohanshenoy96** [comment]
Hi @kmcquade. I have added Vue Router implementation to the navigation bar. Please verify if everything is in place. If u need more implementation on this let me know.

**Comment by kmcquade** [comment]
Fixed by @rohanshenoy96 in #128. Thanks!
