### ISSUE TITLE
Group Memberships not shown in Report

### ISSUE THREAD

**Issue by roock** [salesforce/cloudsplaining#122]
I've created an report from our accounts and the group member ships of users are not shown in the report.
I'm attaching a screenshot with the report and the corresponding IAM group membership page.
![groups_blur](https://user-images.githubusercontent.com/533172/95476369-77cb9e00-0987-11eb-902d-99bafb12d93b.png)
![report_blur](https://user-images.githubusercontent.com/533172/95476375-78fccb00-0987-11eb-9b35-c3f781325a8b.png)

**Comment by ajksharma** [comment]
Can confirm this with my own report.

**Comment by verkaufer** [comment]
@kmcquade I'll look into this. Have you checked if this is a python vs js issue?

**Comment by verkaufer** [comment]
@roock Can you confirm that you see the missing groups listed under the `Groups` heading in the `IAM Principals` page?

**Comment by roock** [comment]
> @roock Can you confirm that you see the missing groups listed under the `Groups` heading in the `IAM Principals` page?

@verkaufer  I can confirm that I see the missing groups under the `Groups` heading in the `IAM principals` page

**Comment by verkaufer** [comment]
Thanks for confirming! I'll see if I'm able to reproduce with a similar input.

**Comment by verkaufer** [comment]
@roock This is resolved in the latest release :) Thanks for reporting!
