### ISSUE TITLE
Set custom file attributes on the report according to the types of findings found

### ISSUE THREAD

**Issue by kmcquade** [salesforce/cloudsplaining#129]
I have a project where we are looping through the reports and creating a big summary table of a lot of AWS accounts. It basically lists out the accounts and a relative path link to the report via `<a href>`. But just by looking at the file, we can't determine how many findings it has, what types of findings, or even the account ID. We are kind of relying on file paths etc. 

I think it would help a lot of other people with this scalability problem if we could leverage `os.setxattr` on the rendered HTML file to set custom attributes about the report. Specifically, I'd like these attributes to be available:

* AccountId (str)
* PrivilegeEscalation (int, total number of findings for that account)
* ResourceExposure (int)
* InfrastructureModification (int)
* DataExfiltration (int)
* AWSManagedPolicies (int)
* CustomerManagedPolicies (int)
* InlinePolicies (int)

If anyone is interested in helping on this, help would be greatly appreciated!!!

**Comment by rohanshenoy96** [comment]
@kmcquade. Is this implementation on UI side? Explanation is bit unclear on what exactly is required

**Comment by kmcquade** [comment]
I did some experimentation with this and determined that we shouldn't pursue this for now. It would likely introduce some dependencies and create issues specific to different OSes. Closing.
