### ISSUE TITLE
Help wanted: Web App for scanning single policy files

### ISSUE THREAD

**Issue by kmcquade** [salesforce/cloudsplaining#131]
It would be great if we could have a web app that allows users to scan a single policy file. 

Parliament (an IAM linting tool) has this: 
* Web app: https://parliament.summitroute.com/
* Relevant GitHub issue: https://github.com/duo-labs/parliament/issues/82

I'd essentially want it to be the same thing.

This would consist of:
* Lambda to run Cloudsplaining on a single policy file (Python)
* Put an API Gateway in front of it
* Host the static files in S3 with CloudFront on top
* Frontend

It'll be just a public site. No logins or tracking of users.

The Lambda would essentially call `cloudsplaining.command.scan_policy`, as shown here:

https://github.com/salesforce/cloudsplaining/blob/759e0bbc552b5d12d836a79e43c2ee947a8772c7/cloudsplaining/command/scan_policy_file.py#L134-L145

If anyone wants to help put this together, we are happy to host it on our infrastructure

**Comment by kmcquade** [comment]
@rohanshenoy96 I am going to add you to an internal repository where we are working on this - you would probably be interested in the UI side.

**Comment by rohanshenoy96** [comment]
Sure @kmcquade

**Comment by kmcquade** [comment]
I'm going to close this issue since we are going to release a public API that will make this possible.
