### ISSUE TITLE
Allow users to copy links to policy findings

### ISSUE THREAD

**Issue by kmcquade** [salesforce/cloudsplaining#133]
If you run `npm serve` on your local machine and paste the following, you will see that this link brings you directly to the policy finding for InlinePolicyForBidenGroup, thanks to @rohanshenoy96 's work on the Vue Router.

http://localhost:8080/#/inline-policy.e8bca32ff7d1f7990d71c64d95a04b7caa5aad5791f06f69db59653228c6853d.card

That is fantastic. But ideally we want people to be able to copy that as a link. Think of when you hover over a header section in Markdown. 
![image](https://user-images.githubusercontent.com/3422255/96890102-4f4aa600-1455-11eb-8490-b5825c962117.png)

**Comment by verkaufer** [comment]
Do we want to support linking to each card (i.e. each row for the rendered results)? I can take a stab at this.

**Comment by kmcquade** [comment]
oooo that would be legit

**Comment by kmcquade** [comment]
Fixed by #151
