### ISSUE TITLE
Add GitHub action to publish directly to Homebrew instead of custom tap

### ISSUE THREAD

**Issue by nitrocode** [salesforce/cloudsplaining#155]
Why maintain a custom tap when this app can be contributed directly to homebrew ?

Great app by the way!

**Comment by kmcquade** [comment]
Thanks! 

@nitrocode  Uh, because I hadn't figured that out before and this worked when I put it together? 😁 lol. Not sure what that entails

**Comment by kmcquade** [comment]
If anyone wants to help with adding this to homebrew directly, that would be greatly appreciated!

**Comment by kmcquade** [comment]
I am going to close this issue. It seems like Homebrew proper requires you to make a pull request, and someone has to approve it. This is why Checkov is currently out of date by 10 days. I don't want to do that - I want the brew installation to be available immediately. https://github.com/Homebrew/homebrew-core/blob/master/Formula/checkov.rb

So, we will maintain a custom tap.
