### ISSUE TITLE
IAM Results mis-reporting Custome policies

### ISSUE THREAD

**Issue by naveenkumar199901** [salesforce/cloudsplaining#174]
I have run Cloudsplaining against an AWS account and the default.json contains one of the for application specific policy but scan only three and exclude one in the account. It shows that the following Attached Custom Policies are part of the Application .
![image](https://user-images.githubusercontent.com/45354703/113570153-67903500-9631-11eb-8907-970b125bb971.png)
But One Policy that is the application specific not scan can you please that s name Resource Policy bot show in the list

**Comment by kmcquade** [comment]
@naveenkumar199901 You mentioned 4 policies, but your screenshot only shows 3. I'm not sure how to answer your question without all the information.

The default exclusions file is here: https://github.com/salesforce/cloudsplaining/blob/master/cloudsplaining/shared/default-exclusions.yml

If Cloudsplaining is not scanning one of the customer managed policies, then it likely matches a pattern in the default exclusions file or your own custom exclusions file. You can adjust your custom exclusions file to fit your needs and match the policies that you want.

**Comment by naveenkumar199901** [comment]
this is issue i have customer managed total 6 policy but when scan its only scan above three policy i have also modified the exclusions.yml but always scan above three my exclusions file 
![image](https://user-images.githubusercontent.com/45354703/113664194-f2703e80-96c8-11eb-9f3c-fc57eacdc817.png)

**Comment by kmcquade** [comment]
One possibility: The policies that are skipped are only attached to roles that have the path `role/service-role/*` or policies that have the path `policy/service-role/*`. Try commenting those two lines out and see if it scans them. Then post the screenshot of your exclusions file so I can double check.

**Comment by kmcquade** [comment]
@naveenkumar199901 I am going to close this issue since I haven't heard from you. Please reopen if the above does not work.
