### ISSUE TITLE
Findings identified in "iam-findings-default.json" do not always appear in "iam-report-default.html" 

### ISSUE THREAD

**Issue by ghost** [salesforce/cloudsplaining#193]
CloudSplaining identified a finding in its "iam-findings-default.json"  file that was not propagated to the "iam-report-default.html"  report. 

Specifically, the JSON file identified that the AWS managed policy "AmazonEC2ContainerRegistryReadOnly" contains Credentials Exposure [ecr:GetAuthorizationToken] but this finding was not reflected in the HTML report.

**Comment by kmcquade** [comment]
I think this is related to the underlying issue in #190, which I just commented on.
