### ISSUE TITLE
the brew package doesn't seem to have fixed the issue fixed by this PR#213

### ISSUE THREAD

**Issue by bksarthak** [salesforce/cloudsplaining#216]
the colors issue mentioned in issue https://github.com/salesforce/cloudsplaining/issues/212 seems to happen if you install from homebrew, but not through pip. Once I installed from pip the report looks fine. I think the homebrew package is outdated.

**Comment by kmcquade** [comment]
Hey, fixing this in #218

**Comment by kmcquade** [comment]
Fixed by #218
