### ISSUE TITLE
Input file scan error - "TypeError: 'PosixPath' object is not iterable"

### ISSUE THREAD

**Issue by Luke-Cmm** [salesforce/cloudsplaining#221]
Hi,

following the documentation I've performed the download (downloaded to [default.json] and when trying to do 'scan' the below message showed up:

> cloudsplaining scan -i default.json
'NoneType' object is not iterable
	Excluded prefix: /service-role*
	Excluded prefix: /aws-service-role*
	Excluded prefix: /aws-service-role*
	Excluded prefix: /aws-service-role*
	Excluded prefix: /aws-service-role*
	Excluded prefix: /aws-service-role*
	Excluded prefix: /aws-service-role*
	Excluded prefix: /aws-service-role*
	Excluded prefix: /aws-service-role*
	Excluded prefix: /service-role*
	Excluded prefix: /aws-service-role*
	Excluded prefix: /aws-service-role*
	Excluded prefix: /aws-service-role*
	Excluded prefix: /aws-service-role*
	Excluded prefix: /aws-service-role*
	Excluded prefix: /aws-service-role*
	Excluded prefix: /aws-service-role*
	Excluded prefix: /aws-service-role*
	Excluded prefix: service-role*
	Excluded prefix: /aws-service-role*
	Excluded prefix: /aws-service-role*
	Excluded prefix: /aws-service-role*
	Excluded prefix: /aws-service-role*
	Excluded prefix: /aws-service-role*
	Excluded prefix: /aws-service-role*
	Excluded prefix: /aws-service-role*
	Excluded prefix: /aws-service-role*
	Excluded prefix: /aws-service-role*
	Excluded prefix: /aws-service-role*
	Excluded prefix: /aws-service-role*
	Excluded prefix: /aws-service-role*
	Excluded prefix: /aws-service-role*
	Excluded prefix: /aws-service-role*
	Excluded prefix: /aws-service-role*
	Excluded prefix: /aws-service-role*
	Excluded prefix: service-role*
Traceback (most recent call last):
  File "/home/vagrant/.local/bin/cloudsplaining", line 8, in <module>
    sys.exit(main())
  File "/home/vagrant/.local/lib/python3.8/site-packages/cloudsplaining/bin/cli.py", line 34, in main
    cloudsplaining()
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/vagrant/.local/lib/python3.8/site-packages/cloudsplaining/command/scan.py", line 105, in scan
    rendered_html_report = scan_account_authorization_details(
  File "/home/vagrant/.local/lib/python3.8/site-packages/cloudsplaining/command/scan.py", line 203, in scan_account_authorization_details
    rendered_report = html_report.get_html_report()
  File "/home/vagrant/.local/lib/python3.8/site-packages/cloudsplaining/output/report.py", line 71, in get_html_report
    env = Environment(loader=FileSystemLoader(template_path))  # nosec
  File "/usr/lib/python3/dist-packages/jinja2/loaders.py", line 163, in __init__
    self.searchpath = list(searchpath)
TypeError: 'PosixPath' object is not iterable

Am I missing something? What could be the reason for that?

**Comment by kmcquade** [comment]
That's strange. I haven't seen that before. What version are you running?

**Comment by CharlesMure** [comment]
Hi,

I had the same issues with version 0.4.6 and in my case I was able to fix it. 
I was using an older version of jinja2 (2.10) so I upgraded it to the lastest version (3.0.3) and it worked. 

So there is maybe something around the requirements ? Note that I installed Cloudsplaining using pip3.
Hope it may help !

**Comment by sobi3ch** [comment]
@CharlesMure tip to update jinja to version 3 helped, however this issue title should be update to something like:
> "_TypeError: 'PosixPath' object is not iterable_"

**Comment by kmcquade** [comment]
Thanks for the fix, @sobi3ch. I updated the requirements.txt to the latest Jinja version, changed the title.

For anyone else - just update to the latest version of Jinja2.
