### ISSUE TITLE
CSV Triage Export missing

### ISSUE THREAD

**Issue by Christiansarkodie** [salesforce/cloudsplaining#230]
Hello All!

When running a scan on a single json input file, only two files are generated which are the findings json and html report. The Triage CSV is never generated. I do not see any error indicating anything

Results data saved: /temp/CloudSplaining/iam-results-Test.json
Findings data file saved: /temp/CloudSplaining/iam-findings-Test.json
Wrote HTML results to: /temp/CloudSplaining/iam-report-Test.html
Opening the HTML report

Is there another parameter I am supposed to add to get the CSV to generate? This is version 0.4.6 on Linux.

**Comment by kmcquade** [comment]
Hey @Christiansarkodie, the CSV triage output was removed in a previous version. This was also requested in #186, so I am marking this as a duplicate.
