### ISSUE TITLE
Compute Role Column blank in html report

### ISSUE THREAD

**Issue by Christiansarkodie** [salesforce/cloudsplaining#232]
Hello,

The Compute Role column in the HTML report is blank for all rows. The other columns show a "0" if there are no findings for a particular row. The Compute Role column is completely blank for all rows and I am not sure if this means that there are no findings, or if something did not run correctly. No error on the export.

Thanks.

**Comment by kmcquade** [comment]
HI @Christiansarkodie. I can't reproduce this without sample data. Can you provide the the account authorization details, and sanitize the file? Feel free to ping me out of band if you want to send it privately so I can take a look.

**Comment by gruebel** [comment]
@Christiansarkodie feel free to reach out again, if you still have issues.
