### ISSUE TITLE
KMS External Key exception

### ISSUE THREAD

**Issue by brendan-s1** [salesforce/cloudsplaining#241]
Hello there, in our large account, we are running: python cloudmapper.py collect --account accountName

And after checking EBS Volumes, i'm getting an exception here:
 kms.get_key_rotation_status({'KeyId': 'axxxxxxxx'}): An error occurred (UnsupportedOperationException) when calling the GetKeyRotationStatus operation: arn:aws:kms:us-east-1:1611111111:key/a8xxxxxx origin is EXTERNAL which is not valid for this operation.
  kms.get_key_rotation_status({'KeyId': 'ddxxxxxxxxx'}): An error occurred (UnsupportedOperationException) when calling the GetKeyRotationStatus operation: arn:aws:kms:us-east-1:16111111111:key/ddxxxxxx origin is EXTERNAL which is not valid for this operation.

**Comment by kmcquade** [comment]
Hey @brendan-s1 - wrong repository :) You're looking for https://github.com/duo-labs/cloudmapper

**Comment by brendan-s1** [comment]
LOL, that's embarrassing. =) Thanks.
