### ISSUE TITLE
Migrate from Vue 2 -> Vue 3 and upgrade dependencies

### ISSUE THREAD

**Issue by kmcquade** [salesforce/cloudsplaining#265]
There's a lot of work that would need to be done to upgrade the report to use Vue 3, which is almost 2 years old at this point (Cloudsplaining uses Vue 2). I know there is some work required to upgrade the report to use Vue 3, but I don't have capacity for it right now.

I'd also like to get some upgrades to the Javascript dependencies since they are outdated but can't seem to upgrade them without everything breaking.

This issue would be great for anyone who has experience with Vue!

If anyone is interested in helping out or collaborating, please ping me.

**Comment by Arnab7456** [comment]
<template>
  <div>Name: {{ name }}</div>
</template>
<script>
import { ref } from "vue";
export default {
  setup() {
    const name = ref('Name');
    return { name };
  }
};
</script>

**Comment by kmcquade** [comment]
@Arnab7456 ... you just pasted code, did you mean to say something else?

**Comment by Jyotika999** [comment]
Hey @kmcquade can you guide how to solve this issue?

**Comment by SD007CSE** [comment]
I fixed a little much of the code in main.js if you want more changes let me know.

**Comment by kmcquade** [comment]
I'm not really maintaining this anymore, and tbh it works in the current state with Vue 2. I am going to close this since I don't think there's a point in upgrading to Vue 3 at this time.
