### ISSUE TITLE
Not able to run the tool

### ISSUE THREAD

**Issue by KishorBal** [salesforce/cloudsplaining#267]
I already have installed the cloudsplaining with pip3 , but i am getting command not found error when trying to execute the tool.
![image](https://user-images.githubusercontent.com/68984199/163308136-55e1d77d-e840-4d65-a757-01b1d391144a.png)

**Comment by kmcquade** [comment]
I think this is an issue with your path. Can you run `echo $PATH` and show your results?

**Comment by QAInsights** [comment]
@KishorBal Please add the `cloudsplaining` software to the PATH. e.g. `export PATH=$PATH:/home/<user_name>/.local/bin`
