### ISSUE TITLE
(InvalidClientTokenId) when calling the GetAccountAuthorizationDetails operation

### ISSUE THREAD

**Issue by yf-odyssey** [salesforce/cloudsplaining#282]
Dear All,
    I have installed the cloudsplaining and configurated the AWS CLI correctly. But when I run the _cloudsplaining download_ error occurs. The screenshot is as below.
<img width="923" alt="1" src="https://user-images.githubusercontent.com/33337184/199697017-ef783904-ca83-4866-94af-20e7d19cbee1.png">

   I am sure the ak/sk is valid and has securityaudit privilege. Because I can successfully run the _aws iam get-account-authorization-details --profile audit_, just as below shows. I also dont't using CLI MFA.
![image](https://user-images.githubusercontent.com/33337184/199697073-53ec10b1-0900-463b-b282-731520c7545e.png)

So could you help me to find out the problem? Thanks a lot!

BTW, Our aws region is AWS China. Is it related to the problem？

**Comment by yf-odyssey** [comment]
@kmcquade hi，could you help me to find out the problem？Thanks a lot!

**Comment by kmcquade** [comment]
yeah I can almost guarantee it's the AWS region being AWS china. IIRC it's hardcoded to be AWS in some cases.

I don't have capacity to make any fix like this, as I'm tied up with my startup. If you or anyone else wants to take this on and make a pull request with a fix, and it passes the unit tests, I can go ahead and approve/merge. Note that this would probably be a good opportunity to ensure compatibility with partitions other than `aws` or `aws-cn` like GovCloud or whatever the CIA abbreviation one is.

**Comment by kmcquade** [comment]
You could try saving the output of `aws iam get-account-authorization-details --profile audit` to a JSON file and then pumping that into Cloudsplaining - that might work. The `cloudsplaining download` command is just a simple wrapper for `aws iam get-account-authorization-details` so at least the input would work.

If that fails, and you don't want to make a PR for the tool, you could do another ugly workaround where you replace all instances of `arn:aws-cn` with `arn:aws` in the JSON output. Cloudsplaining would definitely accept that.

Sorry I can't be of more help. I just have other commitments that prevent me from being involved with the project at this point.

**Comment by yf-odyssey** [comment]
@kmcquade Thanks for your response. I'll try as you said and reply if I have any results.

**Comment by yf-odyssey** [comment]
@kmcquade    Hi, I tried as you said and first saving the output of aws iam get-account-authorization-details --profile audit to a JSON file. Then using Cloudsplaining to check the json file and it works. Thanks a lot!
