### ISSUE TITLE
Unable to identify "Policy leveraged by Compute Service Role"

### ISSUE THREAD

**Issue by amarjaiswal-007** [salesforce/cloudsplaining#287]
As mentioned in the sample cloudsplaining report [here](https://opensource.salesforce.com/cloudsplaining/#/customer-policies#managed.vepermissions)
If I create a Service Role (Which can be assumed by a Compute Service like EC2) and assign excessive permission policies to it.
Upon running cloudsplaining scan it should show that policy under `Policy leveraged by Compute Service Role` (screenshots attached)
![image](https://user-images.githubusercontent.com/113889078/210503738-08814fdc-9f5a-47f2-82c4-0c4bfcdffe92.png)

To test this, I created a similar policy with excessive permissions  
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "VisualEditor0",
      "Effect": "Allow",
      "Action": [
        "s3:*",
        "secretsmanager:*",
        "lambda:*"
      ],
      "Resource": [
        "*"
      ]
    }
  ]
}
```

And created a Role assumable by EC2 with a role trust policy as follows:

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Service": "ec2.amazonaws.com"
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
```

After running the scan, the report didn't identify this policy under `"Policy leveraged by Compute Service Role"`. (attached screenshot)
Am I doing something wrong? or this is not supported by cloudsplaining anymore? Please help! 
![image](https://user-images.githubusercontent.com/113889078/210507234-8d7ca6b4-5f1e-4c3e-a807-4a7edd05bb21.png)

**Comment by kmcquade** [comment]
It skips service roles. I realize this is a potential gap, but it led to a **lot** of false positives.

https://github.com/salesforce/cloudsplaining/blob/master/cloudsplaining/shared/default-exclusions.yml#L14-L16

If you are creating service roles, you can get around this by specifying a custom exclusions file. Feel free to copy that one to your own config file and then modify it to remove one or more of those lines
