### ISSUE TITLE
remove checks against '/aws-service-role/'

### ISSUE THREAD

**Issue by kmcquade** [salesforce/cloudsplaining#41]
I initially excluded that because I assumed that AWS created roles would show up there, which would pollute the results. I do exclude Service Linked Roles (`aws-service-role`) but I am not sure if `service-role` is exclusively reserved for users if it is shared by both AWS and Customers, or encouraged for just customers.

Input from anyone is appreciated.

**Comment by mr-brody** [comment]
As you pointed out, service roles use a specified prefix of '/aws-service-role/'. This is a reserved value which prevents customers from using it. On the other hand, the prefix of '/service-role/' has no such restrictions and there are cases where an AWS service can be granted more permissions than needed and can be abused, ie, ec2. The 'service-role' predates 'service-linked-role' but many services don't use service-linked roles, at least not yet. 

I would suggest providing a check against roles with '/service-role/' and remove checks against '/aws-service-role/', the later of which has immutable permissions from an AWS customer perspective.

**Comment by kmcquade** [comment]
@mr-brody Thanks, yeah I figured out the bit about `service-role` a little while ago. Only issue here is that checking for `/service-role/` prefix without determining if it was created by AWS or by the customer would result in a ton of false positives.

Perhaps we should provide a big disclaimer that you should consider removing that path from the exclusions file? Alternatively, we could provide it as a command flag. I think the latter might be the best way to go.

Let me know what you think.
