### ISSUE TITLE
Triage within table instead of worksheet (pre-defined dropdown for justifications, text field for comments, etc.)

### ISSUE THREAD

**Issue by kmcquade** [salesforce/cloudsplaining#42]
We should be able to select policies in the tables where we want to hide due to False Positives, select an item from a pre-defined dropdown for justifications (or a text field), and then export the non-hidden policies.

This will help to address things without needing the triage spreadsheet

**Comment by kmcquade** [comment]
I tried doing some of this myself, but I couldn’t figure out how to get Datatables Excel export to include (1) the values in a justification text field or (2) the selected drop down value. 

I’m going to mark this as help wanted since I’m having an issue figuring this out, and my JS/UI skills are not the strongest.

If anyone wants to help out here, let me know and I’m happy to discuss.

**Comment by rohanshenoy96** [comment]
Hi @kmcquade.  Can you please give some more information

**Comment by kmcquade** [comment]
Hey @rohanshenoy96, I am actually going to close this one for now because it would require some major changes to be in place before we do that, so it's a while off.

**Comment by rohanshenoy96** [comment]
Cool. Thanks for the update @kmcquade
