### ISSUE TITLE
AWS SSO Inline Policy name to role name mapping

### ISSUE THREAD

**Issue by abdulirfan3** [salesforce/cloudsplaining#48]
when using AWS SSO, i see below under customer polices(we have tons of those, inline policy with same Naming convention)... the issue is, all of the policy are showing up as "AwsSSOInlinePolicy" ... any way to map the actual role name for it ?

![image](https://user-images.githubusercontent.com/11415069/82708431-dea02300-9c43-11ea-847e-5feb4939a740.png)

**Comment by kmcquade** [comment]
Abdul, thanks for opening this issue. As discussed over slack, I’ll try to tackle this issue early next week. It will be a useful addition so thank you for flagging.

To summarize your issue (so I don’t forget it later) you have dozens of inline policies with the same name, but different policy contents. You want to know which role the inline Policy is actually associated with, and unless the customer managed policy tab associates it with the principal, that will be hard to track down.

I’ll let you know as soon as this is done. Thanks again.

**Comment by kmcquade** [comment]
Fixed by #49
