### ISSUE TITLE
UI Refactoring and improvements

### ISSUE THREAD

**Issue by kmcquade** [salesforce/cloudsplaining#74]
There are a lot of UI related bugs/enhancements that I have queued up. I'm addressing a lot of those bugs in a major refactoring process I am undergoing right now. I'm still going with the single-file HTML approach, but I'm leveraging Vue.js and some other things to display the results in a more efficient way for readers. 

If anyone is interested in helping out or collaborating, please ping me.

**Comment by verkaufer** [comment]
@kmcquade I'm interested in offering some help! I've got Python and Vue.js experience and would be happy to help wherever it's most needed.

Email is in my profile; let's chat!
